title: [Dein Projektname]
remote_theme: just-the-docs/just-the-docs
description: "Dokumentation für das Projekt"
baseurl: "" # Leerlassen, wenn es auf der Hauptdomain liegt
markdown: kramdown
permalink: pretty
theme: minima
